version: "3"
services:
  master:
    image: mpolatcan/giraph:1.2.0-hadoop-2.7.7-java8
    container_name: master
    hostname: master
    environment:
      HADOOP_DAEMONS: |
        namenode
        secondarynamenode
        resourcemanager
      FS_DEFAULTFS: "hdfs://master:9000"
      YARN_RESOURCEMANAGER_HOSTNAME: "master"
      YARN_SCHEDULER_MINIMUM_ALLOCATION_MB: "128"
      YARN_SCHEDULER_MAXIMUM_ALLOCATION_MB: "8192"
    ports:
      - 50070:50070 # Namenode UI
      - 8088:8088 # Resourcemanager UI Port

  slave:
    image: mpolatcan/giraph:1.2.0-hadoop-2.7.7-java8
    environment:
      HADOOP_DAEMONS: |
        datanode
        nodemanager
      FS_DEFAULTFS: "hdfs://master:9000"
      YARN_RESOURCEMANAGER_HOSTNAME: "master"
      YARN_NODEMANAGER_RESOURCE_MEMORY_MB: "8192"
      YARN_NODEMANAGER_RESOURCE_CPU_VCORES: "2"
    ports:
      - 9864 # Datanode UI Port
      - 8042 # Nodemanager UI Port
    depends_on:
      - master

#hdfs dfs -mkdir -p /user/hduser/input
#hdfs dfs -copyFromLocal tiny_graph.txt /user/hduser/input
#hadoop jar $HADOOP_HOME/share/hadoop/mapreduce/hadoop-mapreduce-examples-2.7.7.jar wordcount /input /output
