version: "3"
services:
  master:
    image: mpolatcan/giraph:1.2.0-hadoop-2.8.5-java8
    container_name: master
    hostname: master
    environment:
      HADOOP_DAEMONS: |
        namenode
        secondarynamenode
        resourcemanager
      FS_DEFAULTFS: "hdfs://master:9000"
      YARN_RESOURCEMANAGER_HOSTNAME: "master"
      YARN_SCHEDULER_MINIMUM_ALLOCATION_MB: "128"
      YARN_SCHEDULER_MAXIMUM_ALLOCATION_MB: "8192"
      GIRAPH_ZKLIST: "zk1:2181;zk2:2181;zk3:2181"
    ports:
      - 50070:50070 # Namenode UI
      - 8088:8088 # Resourcemanager UI Port

  slave:
    image: mpolatcan/giraph:1.2.0-hadoop-2.8.5-java8
    environment:
      HADOOP_DAEMONS: |
        datanode
        nodemanager
      FS_DEFAULTFS: "hdfs://master:9000"
      YARN_RESOURCEMANAGER_HOSTNAME: "master"
      YARN_NODEMANAGER_RESOURCE_MEMORY_MB: "8192"
      YARN_NODEMANAGER_RESOURCE_CPU_VCORES: "2"
      GIRAPH_ZKLIST: "zk1:2181;zk2:2181;zk3:2181"
    ports:
      - 9864 # Datanode UI Port
      - 8042 # Nodemanager UI Port
    depends_on:
      - master

  # -------------------------------- ZOOKEEPER QUORUM ------------------------------------------
  zk1:
    image: zookeeper
    restart: always
    container_name: zk1
    hostname: zk1
    ports:
      - 2181:2181
    environment:
      ZOO_MY_ID: "1"
      ZOO_SERVERS: "server.1=0.0.0.0:2888:3888;2181 server.2=zk2:2888:3888;2181 server.3=zk3:2888:3888;2181"

  zk2:
    image: zookeeper
    restart: always
    hostname: zk2
    container_name: zk2
    ports:
      - 2182:2181
    environment:
      ZOO_MY_ID: "2"
      ZOO_SERVERS: "server.1=zk1:2888:3888;2181 server.2=0.0.0.0:2888:3888;2181 server.3=zk3:2888:3888;2181"

  zk3:
    image: zookeeper
    restart: always
    hostname: zk3
    container_name: zk3
    ports:
      - 2183:2181
    environment:
      ZOO_MY_ID: "3"
      ZOO_SERVERS: "server.1=zk1:2888:3888;2181 server.2=zk2:2888:3888;2181 server.3=0.0.0.0:2888:3888;2181"
  # -------------------------------------------------------------------------------------------
