name: giraph-docker

on:
  push:
    branches:
      - master

jobs:
  build-giraph-image:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        repository: [giraph]
        java_version: [8]
        giraph_version: [1.3.0, 1.2.0, 1.1.0]
        giraph_hadoop_version: [2]
        hadoop_version: [2.10.1, 2.9.2, 2.8.5, 2.7.7]
    steps:
      - uses: actions/checkout@v2
      - run: echo ${{secrets.DOCKER_PASSWORD}} | docker login -u ${{secrets.DOCKER_USERNAME}} --password-stdin
      - run: docker build -q
          -t ${{secrets.DOCKER_USERNAME}}/${{matrix.repository}}:${{matrix.giraph_version}}-hadoop-${{matrix.hadoop_version}}-java${{matrix.java_version}}
          --build-arg GIRAPH_VERSION=${{matrix.giraph_version}}
          --build-arg GIRAPH_HADOOP_VERSION=${{matrix.giraph_hadoop_version}}
          --build-arg HADOOP_VERSION=${{matrix.hadoop_version}}
          --build-arg JAVA_VERSION=${{matrix.java_version}}
          src
      - run: docker push ${{secrets.DOCKER_USERNAME}}/${{matrix.repository}}:${{matrix.giraph_version}}-hadoop-${{matrix.hadoop_version}}-java${{matrix.java_version}}
      - run: docker rmi ${{secrets.DOCKER_USERNAME}}/${{matrix.repository}}:${{matrix.giraph_version}}-hadoop-${{matrix.hadoop_version}}-java${{matrix.java_version}}